name: Deploy Portal Admin [STG]

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: carrinhodigital
  GCP_REGION: us-east1
  GCP_REGION_ZONE: us-east1-a
  NODE_ENV: production
  CI: false

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Create app.yaml
        run: |
          cat > ./app.yaml <<EOF
          runtime: nodejs10
          env_variables:
            REACT_APP_API_URL: https://api.carrinhodigital.co
            NODE_ENV: ${{ env.NODE_ENV }}
          handlers:
            - url: /
              static_files: build/index.html
              upload: build/index.html
              secure: always

            - url: /(.*)
              static_files: build/\1
              upload: build/(.*)
              secure: always
          EOF

      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy
